version: '3'

services:
  # setup nginx main
  nginx-main:
    image: nginx:1.13.7
    container_name: nginx-main
    restart: unless-stopped
    volumes:
      - ./volumes/nginx/conf/:/etc/nginx/conf.d/
      - ./volumes/nginx/cert/wildcard.vivaconagua.org.chained.crt:/etc/nginx/wildcard.vivaconagua.org.chained.crt
      - ./volumes/nginx/cert/wildcard.vivaconagua.org.key:/etc/nginx/wildcard.vivaconagua.org.key
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        ipv4_address: 172.2.0.2

  nginx-pool:
    image: nginx:1.13.7
    container_name: nginx-pool
    restart: unless-stopped
    volumes:
      - ./volumes/nginx-pool/conf/:/etc/nginx/conf.d/
   # networks: default
    networks:
      default:
        ipv4_address: 172.2.10.1


  nginx-mattermost:
    image: nginx:1.13.7
    container_name: nginx-mattermost
    restart: unless-stopped
    volumes:
      - ./volumes/nginx-mattermost/conf/:/etc/nginx/conf.d/
        # networks: default 
    networks:
      default:
        ipv4_address: 172.2.10.2

  ##
  # Pool fontend docker
  ##
  arise:
    image: vivaconagua/arise:latest
    build: ./arise
    container_name: arise
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.1
  
        #  waves-frontend:
        #    image: vivaconagua/waves-frontend:latest
        #    build: ./waves-frontend
        #    container_name: waves-frontend
        #    restart: unless-stopped
        #    networks:
        #      default:
        #        ipv4_address: 172.2.50.2
        
  stream-frontend:
    image: vivaconagua/stream-frontend:latest
    build: ./stream-frontend
    container_name: stream-frontend
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.3

  canal-frontend:
    image: vivaconagua/canal-frontend:latest
    build: ./canal-frontend
    container_name: canal-frontend
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.5

  docu:
    image: nginx:1.13.7
    container_name: docu
    restart: unless-stopped
    volumes:
      - ./volumes/docu/default.conf:/etc/nginx/conf.d/default.conf
      - ./stream-backend/target/scala-2.12/api/:/etc/nginx/html/docu/stream-backend/
        #  - ./volumes/nginax/cert/wildcard.vivaconagua.org.key:/etc/nginx/wildcard.vivaconagua.org.key
    networks:
      default:
        ipv4_address: 172.2.0.10


  ##
  # Pool backend docker
  ##
  drops:
    image: vivaconagua/drops:develop-test
    #build: ./drops
    container_name: drops
    restart: unless-stopped
    volumes:
      - ./volumes/drops/application.conf:/opt/docker/conf/application.conf
    networks:
      default:
        ipv4_address: 172.2.0.3

  stream-backend:
    image: vivaconagua/stream-backend:0.0.2
    #build: ./drops
    container_name: stream-backend
    restart: unless-stopped
    volumes:
      - ./volumes/stream-backend/application.conf:/opt/docker/conf/application.conf
    networks:
      default:
        ipv4_address: 172.2.0.8


  canal-backend:
    image: vivaconagua/canal-backend:latest
    build: ./canal-backend
    container_name: canal-backend
    restart: unless-stopped
    volumes:
      - ./volumes/canal-backend/canal_backend_settings.py:/app/canal/settings.py
    networks:
      default:
        ipv4_address: 172.2.0.33

# start docker in pool-network
networks:
  default:
    external:
      name: pool-network

