version: '3'

services:
  #########
  # Nginx #
  #########

  nginx-main:
    image: nginx:1.13.7
    container_name: nginx-main
    restart: unless-stopped
    volumes:
      - ./routes/nginx-main/conf/:/etc/nginx/conf.d/
      - ./volumes/nginx-main/cert/wildcard.vivaconagua.org.chained.crt:/etc/nginx/wildcard.vivaconagua.org.chained.crt
      - ./volumes/nginx-main/cert/wildcard.vivaconagua.org.key:/etc/nginx/wildcard.vivaconagua.org.key
    ports:
      - 80:80
      - 443:443
    networks:
      pool-network:
        ipv4_address: 172.2.10.1

  nginx-pool:
    image: nginx:1.13.7
    container_name: nginx-pool
    restart: unless-stopped
    volumes:
      - ./routes/nginx-pool/conf/:/etc/nginx/conf.d/
    networks:
      pool-network:
        ipv4_address: 172.2.10.2

  nginx-mattermost:
    image: nginx:1.13.7
    container_name: nginx-mattermost
    restart: unless-stopped
    volumes:
      - ./routes/nginx-mattermost/conf/:/etc/nginx/conf.d/
    networks:
      pool-network:
        ipv4_address: 172.2.10.3

  #########
  # Drops #
  #########
  arise:
    image: vivaconagua/arise:latest
    build: ./repos/arise
    container_name: arise
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.1
  
  drops:
    image: vivaconagua/drops:develop-test
    container_name: drops
    restart: unless-stopped
    links:
      - nats
      - drops-database
    volumes:
      - ./volumes/drops/application.conf:/opt/docker/conf/application.conf
    networks:
      pool-network:
        ipv4_address: 172.2.100.1

  drops-database:
     image: mariadb
     container_name: drops-database
     environment: 
      - MYSQL_DATABASE=drops 
      - MYSQL_USER=drops
      - MYSQL_PASSWORD=drops 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/drops-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.1

  #########
  # Waves #
  #########
  waves-frontend:
    image: vivaconagua/waves-frontend:latest
    build: ./repos/waves-frontend
    container_name: waves-frontend
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.2
  
  waves-backend:
    image: vivaconagua/waves-backend:latest
    build: ./repos/waves-backend
    container_name: waves-backend
    restart: unless-stopped
    links:
      - waves-database
      - nats
    environment:
      - HOST=172.2.200.2
      - USER_NAME=waves
      - PASSWORD=waves
      - DATABASE=waves 
      - OAUTH_BASE_URI=https://stage.vivaconagua.org
      - CLIENT_ID=wavesex
      - CLIENT_SECRET=waves
      - REDIRECT_URI=http://stage.vivaconagua.org/waves/api/v1/oauth
      - JWT_SECRET=“as0d9a08d0a9d8a0sd”
    networks:
      pool-network:
        ipv4_address: 172.2.100.2
   
  waves-database:
     image: mariadb
     container_name: waves-database
     environment: 
      - MYSQL_DATABASE=waves 
      - MYSQL_USER=waves
      - MYSQL_PASSWORD=waves
      - MYSQL_ROOT_PASSWORD=waves
     restart: unless-stopped
     volumes: 
       - ./volumes/waves-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.2

  ##########
  # Stream #
  ##########
  stream-frontend:
    image: vivaconagua/stream-frontend:latest
    build: ./repos/stream-frontend
    container_name: stream-frontend
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.3
  
  stream-backend:
    image: vivaconagua/stream-backend:latest
    container_name: stream-backend
    restart: unless-stopped
    links:
      - stream-database
      - nats
    volumes:
      - ./volumes/stream-backend/application.conf:/opt/docker/conf/application.conf
    networks:
      pool-network:
        ipv4_address: 172.2.100.3

  stream-database:
     image: mariadb
     container_name: stream-database
     environment: 
      - MYSQL_DATABASE=stream 
      - MYSQL_USER=stream
      - MYSQL_PASSWORD=stream 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/stream-database/mysql/:/var/lib/mysql/
     networks:
       pool-network:
         ipv4_address: 172.2.200.3
  
  #############
  # dispenser #
  #############
  dispenser:
    image: vivaconagua/dispenser:develop
    container_name: dispenser
    restart: unless-stopped
    volumes:
      - ./volumes/dispenser/application.conf:/opt/docker/conf/application.conf
      - ./navigation/:/opt/docker/conf/navigation/jsons/
    networks:
      pool-network:
        ipv4_address: 172.2.100.4

  dispenser-database:
    image: mongo
    container_name: dispenser-database
    restart: always
    volumes: 
       - ./volumes/dispenser-database/mongodb/:/data/db/
    networks:
      pool-network:
        ipv4_address: 172.2.200.4

  #########
  # canal #
  #########
  canal-frontend:
    image: vivaconagua/canal-frontend:latest
    build: ./repos/canal-frontend
    environment:
      - "VUE_APP_MM_URL=https://mattermost.stage.vivaconagua.org"
    container_name: canal-frontend
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.50.5
  
  ##########
  # Assets #
  ##########
  assets:
    image: vivaconagua/assets:latest
    build: ./repos/assets
    container_name: assets-backend
    restart: unless-stopped
    volumes:
      - ./volumes/assets/files/:/public/files/
    networks:
      pool-network:
        ipv4_address: 172.2.100.6
  
  ################
  # Architecture #
  ################
  
  nats:
    image: nats:1.0.6
    container_name: pool-nats
    restart: unless-stopped
    networks:
      pool-network:
        ipv4_address: 172.2.150.1
  
  ########
  # Doku #
  ########
  docu:
    image: nginx:1.13.7
    container_name: docu
    restart: unless-stopped
    volumes:
      - ./volumes/docu/default.conf:/etc/nginx/conf.d/default.conf
      - ./stream-backend/target/scala-2.12/api/:/etc/nginx/html/docu/stream-backend/
    networks:
      pool-network:
        ipv4_address: 172.2.60.10
  
networks:
  pool-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.2.0.0/16 
