version: '3'

services:
  # setup nginx main
  nginx-main:
    image: nginx:1.13.7
    container_name: nginx-main
    restart: unless-stopped
    volumes:
      - ./volumes/nginx-main/conf/:/etc/nginx/conf.d/
      - ./volumes/nginx-main/cert/wildcard.vivaconagua.org.chained.crt:/etc/nginx/wildcard.vivaconagua.org.chained.crt
      - ./volumes/nginx-main/cert/wildcard.vivaconagua.org.key:/etc/nginx/wildcard.vivaconagua.org.key
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        ipv4_address: 172.2.10.1

  nginx-pool:
    image: nginx:1.13.7
    container_name: nginx-pool
    restart: unless-stopped
    volumes:
      - ./volumes/nginx-pool/conf/:/etc/nginx/conf.d/
   # networks: default
    networks:
      default:
        ipv4_address: 172.2.10.2

  nginx-mattermost:
    image: nginx:1.13.7
    container_name: nginx-mattermost
    restart: unless-stopped
    volumes:
      - ./volumes/nginx-mattermost/conf/:/etc/nginx/conf.d/
    networks:
      default:
        ipv4_address: 172.2.10.3

  ##
  # Pool fontend docker
  ##
  arise:
    image: vivaconagua/arise:latest
    build: ./arise
    container_name: arise
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.1

  waves-frontend:
    image: vivaconagua/waves-frontend:latest
    build: ./waves-frontend
    container_name: waves-frontend
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.2
        
  stream-frontend:
    image: vivaconagua/stream-frontend:latest
    build: ./stream-frontend
    container_name: stream-frontend
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.3

  canal-frontend:
    image: vivaconagua/canal-frontend:latest
    build: ./canal-frontend
    environment:
      - "VUE_APP_MM_URL=https://mattermost.stage.vivaconagua.org"
    container_name: canal-frontend
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.50.5

  docu:
    image: nginx:1.13.7
    container_name: docu
    restart: unless-stopped
    volumes:
      - ./volumes/docu/default.conf:/etc/nginx/conf.d/default.conf
      - ./stream-backend/target/scala-2.12/api/:/etc/nginx/html/docu/stream-backend/
    networks:
      default:
        ipv4_address: 172.2.60.10


  ##
  # Pool backend docker
  ##
  
  drops:
    image: vivaconagua/drops:develop-test
    #build: ./drops
    container_name: drops
    restart: unless-stopped
    volumes:
      - ./volumes/drops/application.conf:/opt/docker/conf/application.conf
    networks:
      default:
        ipv4_address: 172.2.0.3

  stream-backend:
    image: vivaconagua/stream-backend:latest
    #build: ./drops
    container_name: stream-backend
    restart: unless-stopped
    volumes:
      - ./volumes/stream-backend/application.conf:/opt/docker/conf/application.conf
    networks:
      default:
        ipv4_address: 172.2.0.8

  assets:
    image: vivaconagua/assets:latest
    build: ./assets
    container_name: assets-backend
    restart: unless-stopped
    volumes:
      - ./volumes/assets/files/:/public/files/
    networks:
      default:
        ipv4_address: 172.2.0.100

  waves-backend:
    image: vivaconagua/waves-backend:latest
    build: ./waves-backend
    container_name: waves-backend
    restart: unless-stopped
    environment:
      - HOST=172.2.200.8
      - USER_NAME=waves
      - PASSWORD=waves
      - DATABASE=waves 
   # volumes:
   #  - ./volumes/waves-backend/canal_backend_settings.py:/app/canal/settings.py
    networks:
      default:
        ipv4_address: 172.2.0.101

  dispenser:
    image: vivaconagua/dispenser:latest
    container_name: dispenser
    restart: unless-stopped
    volumes:
      - ./volumes/dispenser/application.conf:/opt/docker/conf/application.conf
      - ./volumes/dispenser/navigations/:/opt/docker/conf/navigation/jsons/
    networks:
      default:
        ipv4_address: 172.2.100.4


  ##
  # Architecture
  ##
  nats:
    image: nats:1.0.6
    container_name: pool-nats
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.2.100.2
  
  # Database
  drops-database:
     image: mariadb
     container_name: drops-database
     environment: 
      - MYSQL_DATABASE=drops 
      - MYSQL_USER=drops
      - MYSQL_PASSWORD=drops 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/drops-database/mysql/:/var/lib/mysql/
     networks:
       default:
         ipv4_address: 172.2.200.2

  stream-database:
     image: mariadb
     container_name: stream-database
     environment: 
      - MYSQL_DATABASE=stream 
      - MYSQL_USER=stream
      - MYSQL_PASSWORD=stream 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/stream-database/mysql/:/var/lib/mysql/
     networks:
       default:
         ipv4_address: 172.2.200.7

  waves-database:
     image: mysql
     container_name: waves-database
     environment: 
      - MYSQL_DATABASE=waves 
      - MYSQL_USER=waves
      - MYSQL_PASSWORD=waves 
      - MYSQL_ROOT_PASSWORD=yes 
     restart: unless-stopped
     volumes: 
       - ./volumes/waves-database/mysql/:/var/lib/mysql/
     networks:
       default:
         ipv4_address: 172.2.200.8

# start docker in pool-network
networks:
  default:
    external:
      name: pool-network
